--- #YAML:1.0
name:               Net-OAuth2-Moosey-Client
version:            0.02
abstract:           OAuth 2.0 client for perl
author:
    - Robin Clarke <robin@robinclarke.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Message:        0
    JSON:                 0
    LWP::UserAgent:       0
    Moose:                0
    MooseX::Log::Log4perl:  0
    MooseX::Types::URI:   0
    Test::Mock::LWP::Dispatch:  0
    Test::More:           0
    Test::NoWarnings:     0
    URI:                  0
    URI::Escape:          0
    YAML:                 0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
